"""Automated DRC verification using Magic for SKY130.

Runs Magic in batch mode to check GDS files against the SKY130 DRC deck.
Requires:
- Magic installed and on PATH
- SKY130 PDK installed (set PDK_ROOT env var or pass pdk_root)
"""

import os
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass
class DRCResult:
    """Result of a DRC run."""
    clean: bool
    error_count: int
    errors: list[str]
    log_path: Path
    cell_name: str

    def summary(self) -> str:
        if self.clean:
            return f"DRC CLEAN: {self.cell_name} — 0 errors"
        return f"DRC FAILED: {self.cell_name} — {self.error_count} errors"


def find_pdk_root() -> Path:
    """Locate the SKY130 PDK root directory."""
    from rekolektion.tech.sky130 import pdk_path
    # pdk_path() returns the variant dir (e.g. .volare/sky130B).
    # Return its parent as PDK_ROOT for backward compat.
    return pdk_path().parent


def run_drc(
    gds_path: str | Path,
    cell_name: str = "",
    pdk_root: str | Path | None = None,
    output_dir: str | Path | None = None,
) -> DRCResult:
    """Run Magic DRC on a GDS file.

    Args:
        gds_path: Path to the GDS file to check.
        cell_name: Top cell name. If empty, uses the first cell found.
        pdk_root: Path to PDK root. Auto-detected if not provided.
        output_dir: Directory for DRC output files. Uses temp dir if not provided.

    Returns:
        DRCResult with error count and details.
    """
    gds_path = Path(gds_path)
    if not gds_path.exists():
        raise FileNotFoundError(f"GDS file not found: {gds_path}")

    if pdk_root is None:
        pdk_root = find_pdk_root()
    pdk_root = Path(pdk_root)

    if output_dir is None:
        output_dir = Path(tempfile.mkdtemp(prefix="rekolektion_drc_"))
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    from rekolektion.tech.sky130 import magic_techfile, magic_rcfile
    techfile = magic_techfile(pdk_root)
    magicrc = magic_rcfile(pdk_root)

    # Build the Magic TCL script. Count via `drc listall why` (walks the
    # full cell hierarchy) rather than `drc count`, which only reports
    # tiles in the currently loaded cell's own geometry and misses all
    # errors inside referenced sub-cells.
    log_path = output_dir / "drc_results.log"
    tcl_script = f"""\
# DRC script generated by rekolektion
tech load {techfile}
gds read {gds_path}
{"" if not cell_name else f"load {cell_name}"}
select top cell
drc catchup
set why_list [drc listall why]

# Count tiles across all rules, and write detailed log.
set total 0
set f [open {log_path} w]
puts $f "DRC Results for {gds_path.name}"
puts $f "Cell: {cell_name or '(top)'}"
puts $f "==============================="
foreach {{msg box_list}} $why_list {{
    set n [llength $box_list]
    incr total $n
    puts $f "\\nViolation ($n tiles): $msg"
    foreach box $box_list {{
        puts $f "  at: $box"
    }}
}}
puts $f "\\n==============================="
puts $f "Total DRC errors: $total"
close $f

puts "DRC_ERROR_COUNT: $total"
quit -noprompt
"""
    tcl_path = output_dir / "run_drc.tcl"
    tcl_path.write_text(tcl_script)

    # Run Magic
    cmd = ["magic", "-dnull", "-noconsole"]
    if magicrc.exists():
        cmd.extend(["-rcfile", str(magicrc)])
    cmd.append(str(tcl_path))

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300,
            cwd=str(output_dir),
        )
    except FileNotFoundError:
        raise RuntimeError(
            "Magic not found on PATH. Install Magic: "
            "http://opencircuitdesign.com/magic/"
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError(f"Magic DRC timed out after 300s on {gds_path}")

    # Parse results
    error_count = 0
    for line in result.stdout.splitlines():
        if "DRC_ERROR_COUNT:" in line:
            try:
                error_count = int(line.split(":")[-1].strip())
            except ValueError:
                pass

    # Parse detailed errors from log. Each "Violation (N tiles): <msg>"
    # line is kept as-is so DRCResult.errors surfaces both the rule text
    # and the per-rule tile count.
    errors: list[str] = []
    if log_path.exists():
        for line in log_path.read_text().splitlines():
            if line.startswith("Violation "):
                errors.append(line)

    return DRCResult(
        clean=(error_count == 0),
        error_count=error_count,
        errors=errors,
        log_path=log_path,
        cell_name=cell_name or "(top)",
    )
