"""SPICE characterization testbenches for 6T SRAM bitcell.

Generates ngspice testbenches for:
1. Static Noise Margin (SNM) — butterfly curve / read margin
2. Write margin — minimum voltage to flip the cell
3. Hold margin — stability with word line off
4. Read/write access time
5. PVT corner sweeps (TT, SS, FF, SF, FS at VDD ± 10%)
"""

from pathlib import Path
from string import Template

from rekolektion.tech.sky130 import (
    NMOS_MODEL, PMOS_MODEL, RULES, SPICE_MODELS,
)


def _pdk_model_path(corner: str = "tt") -> str:
    """Return the .include line for a given corner."""
    return SPICE_MODELS.get(corner, SPICE_MODELS["tt"])


# ---------------------------------------------------------------------------
# Read SNM (Static Noise Margin) testbench
# ---------------------------------------------------------------------------

READ_SNM_TEMPLATE = Template("""\
* Read Static Noise Margin (SNM) Testbench
* Generated by rekolektion
*
* Measures the butterfly curve by sweeping a DC noise source
* inserted at each storage node.
*

.param vdd_val = ${vdd}
.param temp_val = ${temp}

* Include SKY130 models
.lib "${pdk_root}/sky130A/${model_path}" ${corner}

* Include bitcell subcircuit
.include "${bitcell_spice}"

* Supply
Vvdd VDD 0 DC vdd_val
Vvss VSS 0 DC 0

* Bit lines precharged to VDD (read condition)
Vbl  BL  0 DC vdd_val
Vblb BLB 0 DC vdd_val

* Word line ON
Vwl  WL  0 DC vdd_val

* Instantiate bitcell
Xcell BL BLB WL VDD VSS ${subckt_name}

* DC noise sources for butterfly curve
* Sweep Vn1 at Q node, measure QB; then sweep Vn2 at QB, measure Q
Vn1 Q_probe Xcell.Q DC 0
Vn2 QB_probe Xcell.QB DC 0

* Butterfly curve: sweep noise source, measure inverse transfer
.dc Vn1 0 vdd_val 0.01

* Measurements
.meas DC snm_high FIND V(Xcell.QB) WHEN V(Q_probe)=V(Xcell.QB) RISE=1
.meas DC snm_low  FIND V(Xcell.QB) WHEN V(Q_probe)=V(Xcell.QB) FALL=1

.control
run
set hcopypscolor = 1
set color0 = white
set color1 = black
set color2 = blue
set color3 = red
plot V(Xcell.QB) vs V(Q_probe) title "Read SNM Butterfly Curve"
wrdata ${output_prefix}_read_snm.csv V(Xcell.QB) vs V(Q_probe)
.endc

.end
""")


# ---------------------------------------------------------------------------
# Write margin testbench
# ---------------------------------------------------------------------------

WRITE_MARGIN_TEMPLATE = Template("""\
* Write Margin Testbench
* Generated by rekolektion
*
* Determines minimum BL voltage needed to flip the cell state.
* Initial state: Q=VDD, QB=0. BL pulled low, BLB=VDD, WL activated.
* Sweep BL downward and find the trip point.
*

.param vdd_val = ${vdd}
.param temp_val = ${temp}

.lib "${pdk_root}/sky130A/${model_path}" ${corner}
.include "${bitcell_spice}"

Vvdd VDD 0 DC vdd_val
Vvss VSS 0 DC 0

* Word line ON
Vwl WL 0 DC vdd_val

* BLB held at VDD, BL swept down
Vblb BLB 0 DC vdd_val
Vbl  BL  0 DC vdd_val

* Instantiate and initialize cell (Q=VDD, QB=0)
Xcell BL BLB WL VDD VSS ${subckt_name}
.ic V(Xcell.Q) = vdd_val
.ic V(Xcell.QB) = 0

* Sweep BL from VDD down to 0
.dc Vbl vdd_val 0 -0.01

.meas DC write_trip FIND V(BL) WHEN V(Xcell.Q)=V(Xcell.QB)
.meas DC write_margin PARAM='vdd_val - write_trip'

.control
run
wrdata ${output_prefix}_write_margin.csv V(Xcell.Q) V(Xcell.QB)
.endc

.end
""")


# ---------------------------------------------------------------------------
# Hold margin testbench
# ---------------------------------------------------------------------------

HOLD_MARGIN_TEMPLATE = Template("""\
* Hold Margin (Hold SNM) Testbench
* Generated by rekolektion
*
* Word line OFF, measure stability of stored data.
*

.param vdd_val = ${vdd}
.param temp_val = ${temp}

.lib "${pdk_root}/sky130A/${model_path}" ${corner}
.include "${bitcell_spice}"

Vvdd VDD 0 DC vdd_val
Vvss VSS 0 DC 0

* Word line OFF
Vwl WL 0 DC 0

* Bit lines floating (high-Z) — use large resistors
Rbl  BL  VDD 1G
Rblb BLB VDD 1G

Xcell BL BLB WL VDD VSS ${subckt_name}

* Noise source at Q
Vn Q_probe Xcell.Q DC 0

.dc Vn 0 vdd_val 0.01

.control
run
wrdata ${output_prefix}_hold_snm.csv V(Xcell.QB) vs V(Q_probe)
.endc

.end
""")


# ---------------------------------------------------------------------------
# Transient read/write testbench
# ---------------------------------------------------------------------------

TRANSIENT_TEMPLATE = Template("""\
* Transient Read/Write Testbench
* Generated by rekolektion
*
* Sequence: precharge → write 1 → read 1 → write 0 → read 0
*

.param vdd_val = ${vdd}
.param period = 20n
.param temp_val = ${temp}

.lib "${pdk_root}/sky130A/${model_path}" ${corner}
.include "${bitcell_spice}"

Vvdd VDD 0 DC vdd_val
Vvss VSS 0 DC 0

* Word line: pulse during access
Vwl WL 0 PWL(
+  0n      0
+  5n      0
+  5.1n    vdd_val
+  15n     vdd_val
+  15.1n   0
+  25n     0
+  25.1n   vdd_val
+  35n     vdd_val
+  35.1n   0
+  45n     0
+  45.1n   vdd_val
+  55n     vdd_val
+  55.1n   0
+  65n     0
+  65.1n   vdd_val
+  75n     vdd_val
+  75.1n   0
+ )

* BL: precharge to VDD, then drive during write, float during read
Vbl BL_drive 0 PWL(
+  0n      vdd_val
+  5n      vdd_val
+  5.1n    vdd_val
+  15n     vdd_val
+  25n     vdd_val
+  25.1n   0
+  35n     0
+  35.1n   vdd_val
+  55n     vdd_val
+  55.1n   vdd_val
+  75n     vdd_val
+ )
Rbl_drive BL_drive BL 100

* BLB: complement of BL during write
Vblb BLB_drive 0 PWL(
+  0n      vdd_val
+  5n      vdd_val
+  5.1n    0
+  15n     0
+  15.1n   vdd_val
+  25n     vdd_val
+  25.1n   vdd_val
+  35n     vdd_val
+  35.1n   vdd_val
+  55n     vdd_val
+  55.1n   0
+  75n     0
+ )
Rblb_drive BLB_drive BLB 100

* Bit line capacitance (typical column load)
Cbl  BL  0 50f
Cblb BLB 0 50f

Xcell BL BLB WL VDD VSS ${subckt_name}

.tran 0.01n 80n

.control
run
wrdata ${output_prefix}_transient.csv V(BL) V(BLB) V(WL) V(Xcell.Q) V(Xcell.QB)
.endc

.end
""")


def generate_testbenches(
    bitcell_spice: str | Path,
    output_dir: str | Path = ".",
    corners: list[str] | None = None,
    voltages: list[float] | None = None,
    temperatures: list[float] | None = None,
) -> list[Path]:
    """Generate all characterization testbenches for the 6T bitcell.

    Args:
        bitcell_spice: Path to the bitcell SPICE netlist.
        output_dir: Directory for generated testbench files.
        corners: Process corners to sweep. Default: ["tt", "ss", "ff"].
        voltages: Supply voltages. Default: [1.62, 1.8, 1.98].
        temperatures: Temperatures in C. Default: [-40, 27, 125].

    Returns:
        List of paths to generated testbench files.
    """
    if corners is None:
        corners = ["tt", "ss", "ff"]
    if voltages is None:
        voltages = [RULES.VDD_MIN, RULES.VDD_NOMINAL, RULES.VDD_MAX]
    if temperatures is None:
        temperatures = [-40.0, 27.0, 125.0]

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    bitcell_spice = Path(bitcell_spice).resolve()

    # Extract subcircuit name from the netlist file
    subckt_name = "sky130_sram_6t_bitcell"  # default
    for line in bitcell_spice.read_text().splitlines():
        if line.strip().lower().startswith(".subckt"):
            subckt_name = line.split()[1]
            break

    generated: list[Path] = []

    templates = {
        "read_snm": READ_SNM_TEMPLATE,
        "write_margin": WRITE_MARGIN_TEMPLATE,
        "hold_snm": HOLD_MARGIN_TEMPLATE,
        "transient": TRANSIENT_TEMPLATE,
    }

    import os
    pdk_root = os.environ.get("PDK_ROOT", os.path.expanduser("~/.volare"))

    for corner in corners:
        model_lib = SPICE_MODELS.get(corner, SPICE_MODELS["tt"])
        model_path, corner_name = model_lib.rsplit(" ", 1)

        for vdd in voltages:
            for temp in temperatures:
                params = {
                    "vdd": f"{vdd:.2f}",
                    "temp": f"{temp:.1f}",
                    "corner": corner_name,
                    "model_path": model_path,
                    "bitcell_spice": str(bitcell_spice),
                    "output_prefix": f"{corner}_{vdd:.2f}V_{temp:.0f}C",
                    "subckt_name": subckt_name,
                    "pdk_root": pdk_root,
                }

                for name, template in templates.items():
                    filename = f"tb_{name}_{corner}_{vdd:.2f}V_{temp:.0f}C.spice"
                    path = output_dir / filename
                    path.write_text(template.substitute(params))
                    generated.append(path)

    return generated


def run_ngspice(testbench_path: str | Path, timeout: int = 120) -> Path:
    """Run a single ngspice testbench.

    Returns path to the output data file.
    """
    import subprocess

    tb = Path(testbench_path)
    log = tb.with_suffix(".log")

    try:
        result = subprocess.run(
            ["ngspice", "-b", str(tb)],
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(tb.parent),
        )
    except FileNotFoundError:
        raise RuntimeError("ngspice not found on PATH. Install ngspice.")

    log.write_text(result.stdout + "\n" + result.stderr)

    if result.returncode != 0:
        raise RuntimeError(f"ngspice failed on {tb.name}. See {log}")

    return log
