/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSEDSIGNAL */
/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module test_sram(clk, we, cs, addr, din, dout, VPWR, VGND);
  inout VGND;
  wire VGND;
  inout VPWR;
  wire VPWR;
  input [5:0] addr;
  wire [5:0] addr;
  input clk;
  wire clk;
  input cs;
  wire cs;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  wire [7:0] dout;
  input we;
  wire we;
endmodule

/* verilator lint_on UNUSEDSIGNAL */
/* verilator lint_on UNDRIVEN */

