"""Blackbox Verilog generator for digital v2 SRAM macros.

Emits a top-port-only Verilog stub that downstream synthesis tools
(Yosys, OpenLane) read so they can instantiate the macro at chip top
without trying to synthesize its internals. Port list is derived from
the macro's `MacroParams` (words/bits → addr/data widths) and uses the
canonical uppercase port names also emitted by the LEF generator
(`uppercase_ports=True`) and the chip-top RTL.

Pre-2026-05-04: bb.v files were carried forward by hand from v1 macro
output. When v2 generation regenerated `output/v2_macros/<name>/`, the
bb.v stubs were lost and had to be manually recreated, which broke
downstream OpenLane runs at config-load time. This module restores
auto-generation alongside the LEF/Liberty/SPICE outputs.

Usage::

    from rekolektion.macro.blackbox import generate_blackbox
    generate_blackbox(params, "output/v2_macros/sram_weight_bank_small/sram_weight_bank_small_bb.v",
                      macro_name="sram_weight_bank_small")
"""
from __future__ import annotations

from pathlib import Path

from rekolektion.macro.assembler import MacroParams


def generate_blackbox(
    params: MacroParams,
    output_path: str | Path,
    *,
    macro_name: str | None = None,
    pwr_pin: str = "VPWR",
    gnd_pin: str = "VGND",
) -> Path:
    """Generate a blackbox Verilog stub for a digital v2 SRAM macro.

    Parameters
    ----------
    params:
        MacroParams describing the macro (words, bits, mux_ratio).
        ADDR width is derived as `params.num_addr_bits` (= log2(words)).
        DIN/DOUT widths are `params.bits`.
    output_path:
        File path for the generated `_bb.v`.
    macro_name:
        Verilog module name. Defaults to `params.top_cell_name`. The LEF
        generator's `--macro-name` override and the chip-top RTL's
        instantiation must match this string.
    pwr_pin / gnd_pin:
        Power pin names. Match the LEF (default VPWR/VGND).
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    if not macro_name:
        macro_name = params.top_cell_name

    addr_w = params.num_addr_bits
    data_w = params.bits

    lines = [
        f"// Blackbox Verilog stub for {macro_name}",
        f"// {params.words} words x {data_w} bits (mux={params.mux_ratio})",
        f"// Generated by rekolektion (rekolektion.macro.blackbox)",
        f"",
        f"(* blackbox *)",
        f"module {macro_name} (",
        f"`ifdef USE_POWER_PINS",
        f"    inout  wire               {pwr_pin},",
        f"    inout  wire               {gnd_pin},",
        f"`endif",
        f"    input  wire               CLK,",
        f"    input  wire               WE,",
        f"    input  wire               CS,",
        f"    input  wire [{addr_w - 1}:0]  ADDR,",
        f"    input  wire [{data_w - 1}:0]  DIN,",
        f"    output wire [{data_w - 1}:0]  DOUT",
        f");",
        f"endmodule",
        f"",
    ]
    out.write_text("\n".join(lines))
    return out
