"""MBL precharge row for CIM macros.

Tiles `cols` MBL precharge cells horizontally (one per bitcell column),
sitting at the TOP edge of the array.  Mirrors v2 SRAM's
PrechargeRow pattern — a single common control signal (`MBL_PRE`)
plus per-column MBL connections (auto-abutted to the array's MBL
columns) and a global VREF.

The MBL precharge cell is generated by
`rekolektion.peripherals.cim_mbl_precharge.generate_mbl_precharge()` —
1.20 × 1.17 µm with internal labels `MBL_PRE`, `VREF`, `MBL`.
"""
from __future__ import annotations

from typing import Optional

import gdstk

from rekolektion.peripherals.cim_mbl_precharge import generate_mbl_precharge
from rekolektion.macro.routing import draw_pin_with_label
from rekolektion.macro.sky130_drc import GDS_LAYER


_PRE_CELL_NAME: str = "cim_mbl_precharge"

# Internal label positions on the cim_mbl_precharge cell (verified by
# inspecting cell.labels after generate_mbl_precharge()):
#   MBL_PRE @ (0.170, 0.705) on poly  — gate input
#   VREF    @ (0.720, 0.955) on li1   — top S/D (PMOS source)
#   MBL     @ (0.720, 0.455) on li1   — bottom S/D (PMOS drain)
#   VPWR    @ (1.560, 0.705) on met1  — N-tap
_MBL_PRE_LX: float = 0.170
_MBL_PRE_LY: float = 0.705
_VREF_LX:    float = 0.720
_VREF_LY:    float = 0.955
_MBL_LX:     float = 0.720
_MBL_LY:     float = 0.455
_VPWR_LX:    float = 1.560
_VPWR_LY:    float = 0.705
_PRE_CELL_W: float = 1.790
_PRE_CELL_H: float = 1.170


class MBLPrechargeRow:
    """Row of `cols` MBL precharge cells across the top of the array."""

    def __init__(
        self,
        cols: int,
        col_pitch: float,
        name: Optional[str] = None,
        strap_interval: int = 0,
        strap_width: float = 0.0,
    ):
        if cols < 1:
            raise ValueError(f"cols must be >= 1; got {cols}")
        if col_pitch <= 0:
            raise ValueError(f"col_pitch must be positive; got {col_pitch}")
        self.cols = cols
        self.col_pitch = col_pitch
        # Strap insertion (CIM tap supercell columns inserted in the
        # array every `strap_interval` bitcell columns).  When > 0,
        # periphery cell placement and pin X positions skip the strap
        # column slots so they stay aligned with bitcell columns;
        # horizontal bus stripes extend across the strap-column gap.
        # `strap_width` defaults to `col_pitch` (matching the array's
        # tap supercell width = bitcell pitch).
        self.strap_interval = max(0, int(strap_interval))
        self.strap_width = (
            strap_width if strap_width > 0.0 else col_pitch
        ) if self.strap_interval > 0 else 0.0
        self.top_cell_name = name or f"cim_mbl_precharge_row_{cols}"

    @property
    def cell_w(self) -> float:
        return _PRE_CELL_W

    @property
    def cell_h(self) -> float:
        return _PRE_CELL_H

    @property
    def n_strap_cols(self) -> int:
        if self.strap_interval <= 0 or self.cols <= 1:
            return 0
        return (self.cols - 1) // self.strap_interval

    def _col_x(self, col: int) -> float:
        """X-coordinate of bitcell column `col`, strap-aware."""
        if self.strap_interval <= 0:
            return col * self.col_pitch
        n_straps_before = col // self.strap_interval
        return col * self.col_pitch + n_straps_before * self.strap_width

    @property
    def width(self) -> float:
        return self.cols * self.col_pitch + self.n_strap_cols * self.strap_width

    @property
    def height(self) -> float:
        return self.cell_h

    def build(self) -> gdstk.Library:
        lib = gdstk.Library(name=f"{self.top_cell_name}_lib")
        top = gdstk.Cell(self.top_cell_name)

        pre_cell, pre_lib = generate_mbl_precharge()
        seen: set[str] = set()
        for c in pre_lib.cells:
            if c.name not in seen:
                lib.add(c.copy(c.name))
                seen.add(c.name)
        local_pre = next(c for c in lib.cells if c.name == _PRE_CELL_NAME)

        # Place one precharge per BITCELL column at strap-aware X.
        # Centre each cell in the column's pitch (so the cell's MBL
        # output sits roughly at the column's bitcell MBL x position).
        # Strap columns get NO precharge cell; the horizontal bus
        # stripes carry across the strap-column gap unbroken.
        x_offset = (self.col_pitch - self.cell_w) / 2.0
        for col in range(self.cols):
            origin = (self._col_x(col) + x_offset, 0.0)
            top.add(gdstk.Reference(local_pre, origin=origin))

        # Horizontal shared-bus stripes spanning the full row width.
        # Each connects the per-cell pin position across all columns
        # into a single named net.  Layer must match the cell's pin
        # layer at that Y so the stripes physically merge with the
        # underlying cell poly/li1/met1.
        row_w = self.width
        poly_id, poly_dt = GDS_LAYER["poly"]
        li1_id, li1_dt = GDS_LAYER["li1"]
        m1_id, m1_dt = GDS_LAYER["met1"]
        _BUS_HALF = 0.075   # bus half-width

        # MBL_PRE bus on poly at Y=_MBL_PRE_LY (0.705)
        top.add(gdstk.rectangle(
            (0.0, _MBL_PRE_LY - _BUS_HALF),
            (row_w, _MBL_PRE_LY + _BUS_HALF),
            layer=poly_id, datatype=poly_dt,
        ))
        # VREF bus on li1 at Y=_VREF_LY (0.955)
        top.add(gdstk.rectangle(
            (0.0, _VREF_LY - _BUS_HALF),
            (row_w, _VREF_LY + _BUS_HALF),
            layer=li1_id, datatype=li1_dt,
        ))
        # VPWR bus on met1 at Y=_VPWR_LY (0.705)
        top.add(gdstk.rectangle(
            (0.0, _VPWR_LY - _BUS_HALF),
            (row_w, _VPWR_LY + _BUS_HALF),
            layer=m1_id, datatype=m1_dt,
        ))

        # Pin shapes are placed AT the cell's actual pin coordinates
        # ON the cell's actual pin layers — otherwise the parent .pin
        # is electrically isolated from the underlying net and Magic
        # extracts both as separate floating nodes.
        #
        # cim_mbl_precharge pin layers:
        #   MBL_PRE: poly  — gate input
        #   VREF:    li1   — top S/D pad
        #   MBL:     li1   — bottom S/D pad
        #   VPWR:    met1  — N-tap pad
        _PIN_HALF = 0.07
        for col in range(self.cols):
            x_origin = self._col_x(col) + x_offset

            # MBL_PRE — shared row-wide bus, .pin on poly at cell's
            # MBL_PRE position
            cx = x_origin + _MBL_PRE_LX
            cy = _MBL_PRE_LY
            draw_pin_with_label(
                top, text="MBL_PRE", layer="poly",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # VREF — shared row-wide bus, .pin on li1 at cell's VREF S/D
            cx = x_origin + _VREF_LX
            cy = _VREF_LY
            draw_pin_with_label(
                top, text="VREF", layer="li1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # MBL[col] — per-column drain, .pin on li1 at cell's MBL S/D
            cx = x_origin + _MBL_LX
            cy = _MBL_LY
            draw_pin_with_label(
                top, text=f"MBL[{col}]", layer="li1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # VPWR — shared, .pin on met1 at the N-tap position
            cx = x_origin + _VPWR_LX
            cy = _VPWR_LY
            draw_pin_with_label(
                top, text="VPWR", layer="met1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

        lib.add(top)
        return lib
