"""Blackbox Verilog generator for CIM SRAM macros.

Generates synthesis-compatible blackbox stubs that declare the macro's
port interface without any implementation. Required by Yosys/OpenLane
for hierarchical synthesis.

Usage::

    from rekolektion.macro.cim_blackbox import generate_cim_blackbox
    generate_cim_blackbox(params, "output/cim_sram_c_64x64_bb.v")
"""

from __future__ import annotations

from pathlib import Path

from rekolektion.macro.cim_assembler import CIMMacroParams


def generate_cim_blackbox(
    params: CIMMacroParams,
    output_path: str | Path,
    macro_name: str | None = None,
    *,
    pwr_pin: str = "VPWR",
    gnd_pin: str = "VGND",
) -> Path:
    """Generate a blackbox Verilog stub for a CIM SRAM macro."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    rows = params.rows
    cols = params.cols
    if not macro_name:
        macro_name = f"cim_{params.variant.lower().replace('-', '_')}_{rows}x{cols}"

    lines = [
        f"// Blackbox stub for {macro_name}",
        f"// CIM SRAM array: {rows} rows x {cols} columns",
        f"// MIM cap: {params.mim_w:.2f} x {params.mim_l:.2f} um (~{params.cap_fF:.0f} fF)",
        f"// Generated by rekolektion",
        f"",
        f"(* blackbox *)",
        f"module {macro_name} (",
    ]

    # Port list — bus ports declared as Verilog arrays so the
    # `MWL_EN[i]` / `MBL_OUT[c]` names round-trip with the LEF (which
    # also uses bracketed notation per its `BUSBITCHARS "[]"` header)
    # and the Liberty `bus (MWL_EN)` declaration.  Per-bit underscore
    # ports (MWL_EN_0, ...) read fine on their own but break LEF↔V
    # connectivity in any P&R / synthesis flow that walks the LEF
    # MACRO pin list and expects the same names in the Verilog stub.
    ports = [
        f"    input  [{rows - 1}:0] MWL_EN",
        f"    output [{cols - 1}:0] MBL_OUT",
        f"    input  MBL_PRE",
        f"    inout  VREF",
        f"    input  VBIAS",
        f"    inout  {pwr_pin}",
        f"    inout  {gnd_pin}",
    ]
    lines.append(",\n".join(ports))
    lines += [
        f");",
        f"endmodule",
        f"",
    ]

    out.write_text("\n".join(lines))
    return out
