"""MBL sense buffer row for CIM macros.

Tiles `cols` MBL sense cells horizontally at the BOTTOM edge of the
array (one per column).  Each cell exposes a per-column MBL_OUT[col]
output plus shared VBIAS (analog bias) and supplies.

The MBL sense cell is generated by
`rekolektion.peripherals.cim_mbl_sense.generate_mbl_sense()` —
1.26 × 1.73 µm with internal labels `VBIAS`, `MBL`, `VSS`,
`MBL_OUT`, `VDD`.
"""
from __future__ import annotations

from typing import Optional

import gdstk

from rekolektion.peripherals.cim_mbl_sense import generate_mbl_sense
from rekolektion.macro.routing import draw_pin_with_label


_SENSE_CELL_NAME: str = "cim_mbl_sense"


class MBLSenseRow:
    """Row of `cols` MBL sense buffers at the bottom edge of the array."""

    def __init__(
        self,
        cols: int,
        col_pitch: float,
        name: Optional[str] = None,
    ):
        if cols < 1:
            raise ValueError(f"cols must be >= 1; got {cols}")
        if col_pitch <= 0:
            raise ValueError(f"col_pitch must be positive; got {col_pitch}")
        self.cols = cols
        self.col_pitch = col_pitch
        self.top_cell_name = name or f"cim_mbl_sense_row_{cols}"

    @property
    def cell_w(self) -> float:
        return 1.26

    @property
    def cell_h(self) -> float:
        return 1.73

    @property
    def width(self) -> float:
        return self.cols * self.col_pitch

    @property
    def height(self) -> float:
        return self.cell_h

    def build(self) -> gdstk.Library:
        lib = gdstk.Library(name=f"{self.top_cell_name}_lib")
        top = gdstk.Cell(self.top_cell_name)

        sense_cell, sense_lib = generate_mbl_sense()
        seen: set[str] = set()
        for c in sense_lib.cells:
            if c.name not in seen:
                lib.add(c.copy(c.name))
                seen.add(c.name)
        local_sense = next(c for c in lib.cells if c.name == _SENSE_CELL_NAME)

        x_offset = (self.col_pitch - self.cell_w) / 2.0
        for col in range(self.cols):
            origin = (col * self.col_pitch + x_offset, 0.0)
            top.add(gdstk.Reference(local_sense, origin=origin))

        # Port .pin shapes: per-col MBL_OUT[col], shared VBIAS, supplies.
        _PIN_HALF = 0.07
        for col in range(self.cols):
            base_x = col * self.col_pitch + x_offset + self.cell_w / 2.0
            # MBL_OUT — per-column output at the cell BOTTOM (south
            # edge of macro) so it can become a top-level macro pin.
            mbl_out_y = 0.10
            draw_pin_with_label(
                top, text=f"MBL_OUT[{col}]", layer="met1",
                rect=(base_x - _PIN_HALF, mbl_out_y - _PIN_HALF,
                      base_x + _PIN_HALF, mbl_out_y + _PIN_HALF),
            )
            # VBIAS — shared analog bias, common to all sense cells.
            vbias_y = self.cell_h / 2.0
            draw_pin_with_label(
                top, text="VBIAS", layer="met1",
                rect=(base_x - _PIN_HALF, vbias_y - _PIN_HALF,
                      base_x + _PIN_HALF, vbias_y + _PIN_HALF),
            )
            # MBL[col] — input from the bitcell column (TOP edge,
            # abuts the array's MBL routing).
            mbl_in_y = self.cell_h - 0.10
            draw_pin_with_label(
                top, text=f"MBL[{col}]", layer="met1",
                rect=(base_x - _PIN_HALF, mbl_in_y - _PIN_HALF,
                      base_x + _PIN_HALF, mbl_in_y + _PIN_HALF),
            )
            # VPWR / VGND — per-cell supplies.
            vpwr_y = self.cell_h - 0.30
            vgnd_y = 0.30
            draw_pin_with_label(
                top, text="VPWR", layer="met1",
                rect=(base_x - _PIN_HALF, vpwr_y - _PIN_HALF,
                      base_x + _PIN_HALF, vpwr_y + _PIN_HALF),
            )
            draw_pin_with_label(
                top, text="VGND", layer="met1",
                rect=(base_x - _PIN_HALF, vgnd_y - _PIN_HALF,
                      base_x + _PIN_HALF, vgnd_y + _PIN_HALF),
            )

        lib.add(top)
        return lib
