"""Reference SPICE generator for CIM macros.

Mirrors the v2 SRAM `spice_generator.py` pattern: emits a self-
contained SPICE deck for the CIM macro composed of:
  1. Pre-extracted .subckt definitions for each CIM building block
     (CIM bitcell variant + the three peripheral cells), pulled from
     `peripherals/cells/extracted_subckt/`.
  2. Top-level `.subckt cim_<variant>_<rows>x<cols>` whose body
     instantiates the array, MWL drivers, MBL precharges, MBL sense
     buffers + wires their ports per the CIM placement contract.

Used as the reference netlist for LVS comparison against the GDS-
extracted netlist of the assembled CIM macro.
"""
from __future__ import annotations

from pathlib import Path
from typing import TextIO

from rekolektion.macro.cim_assembler import CIMMacroParams


_EXTRACTED_DIR: Path = (
    Path(__file__).parent.parent / "peripherals/cells/extracted_subckt"
)


def _bitcell_subckt_filename(variant: str) -> str:
    slug = variant.lower().replace("-", "_")
    return f"sky130_sram_6t_cim_lr_{slug}.subckt.sp"


def _read_extracted(filename: str) -> list[str]:
    """Read an extracted .subckt.sp file's body lines (already
    pre-extracted by `scripts/extract_cim_subckts.py`)."""
    path = _EXTRACTED_DIR / filename
    if not path.exists():
        raise FileNotFoundError(
            f"Missing extracted subckt {path}. Run "
            f"`python3 scripts/extract_cim_subckts.py` first."
        )
    return path.read_text().splitlines()


def _write_extracted(f: TextIO, lines: list[str]) -> None:
    """Write a pre-extracted subckt body verbatim, with a separator."""
    f.write("\n")
    for ln in lines:
        f.write(ln.rstrip() + "\n")
    f.write("\n")


_BITCELL_SCHEMATIC_PATH: Path = (
    Path(__file__).parent.parent.parent.parent / "output/sky130_6t_cim_lr.spice"
)


def _write_bitcell_schematic(f: TextIO) -> None:
    """Inline the hand-written bitcell schematic (validated by
    `scripts/run_lvs_bitcell.py`) as the bitcell .subckt definition.
    The schematic uses fixed cap dims (1.0 × 1.0); device-class topology
    is what LVS compares, not parameter values."""
    if not _BITCELL_SCHEMATIC_PATH.exists():
        raise FileNotFoundError(
            f"Missing bitcell schematic {_BITCELL_SCHEMATIC_PATH}. "
            f"Regenerate with `python3 -c \"from rekolektion.bitcell."
            f"sky130_6t_lr_cim import generate_cim_bitcell; "
            f"generate_cim_bitcell('output/sky130_6t_cim_lr.gds')\"`"
        )
    f.write("\n")
    f.write(_BITCELL_SCHEMATIC_PATH.read_text())
    f.write("\n")


def generate_cim_reference_spice(
    p: CIMMacroParams,
    output_path: str | Path,
    *,
    top_subckt_name: str | None = None,
) -> Path:
    """Generate the reference SPICE deck for a CIM macro.

    Parameters
    ----------
    p : CIMMacroParams
        Variant + dimensions.
    output_path : path
        Where to write the .sp file.
    top_subckt_name : str, optional
        Override the top-level subckt name (default ``p.top_cell_name``).
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    top_name = top_subckt_name or p.top_cell_name
    bitcell_subckt = "sky130_sram_6t_cim_lr"
    mwl_driver_subckt = "sky130_fd_sc_hd__buf_2"

    with out.open("w") as f:
        f.write(
            f"* CIM reference SPICE for {p.variant} ({p.rows}x{p.cols})\n"
            f"* Generated by rekolektion.macro.cim_spice_generator.\n"
            f"* Models VDD/VSS/VSUBS as global supplies.\n"
        )
        f.write(".global VDD VSS VSUBS VPWR VGND\n\n")

        # Per-cell subckt definitions.  MWL driver, MBL precharge, and
        # MBL sense are pre-extracted from layout (small, simple cells).
        # The BITCELL specifically is sourced from the hand-written
        # SCHEMATIC (output/sky130_6t_cim_lr.spice) — track 05 trustworthy
        # LVS fix.  Pre-fix this read the extracted bitcell, which made
        # the macro LVS a self-reference (extracted-vs-extracted, can't
        # catch broken cells).  Now the schematic asserts the bitcell's
        # intended topology and the macro LVS verifies the layout truly
        # implements that topology.  The bitcell schematic uses fixed
        # MIM cap dimensions (1.0 × 1.0); per-variant cap dimensions are
        # sized at the actual layout but netgen compares cap topology
        # only (cap_mim_m3_1 is a 2-terminal class) so this is a safe
        # value-only difference, not a connectivity mismatch.
        _write_extracted(f, _read_extracted(f"{mwl_driver_subckt}.subckt.sp"))
        _write_extracted(f, _read_extracted("cim_mbl_precharge.subckt.sp"))
        _write_extracted(f, _read_extracted("cim_mbl_sense.subckt.sp"))
        _write_bitcell_schematic(f)

        # Top-level subckt port list — matches the macro's external
        # pins as drawn by `cim_assembler.assemble_cim`.  Includes
        # BL/BLB/WL/MWL nets as macro ports because Magic's flat
        # extraction promotes them via the per-row/col labels we
        # add at the cell boundaries (see run_lvs_cim.py).
        ports = (
            [f"MWL_EN[{r}]" for r in range(p.rows)]
            + ["MBL_PRE", "VREF", "VBIAS"]
            + [f"MBL_OUT[{c}]" for c in range(p.cols)]
            + [f"BL_{c}" for c in range(p.cols)]
            + [f"BLB_{c}" for c in range(p.cols)]
            + [f"WL_{r}" for r in range(p.rows)]
            + [f"MWL_{r}" for r in range(p.rows)]
            + [f"MBL_{c}" for c in range(p.cols)]
            + ["VPWR", "VGND"]
        )
        # SPICE doesn't allow brackets in port names by default; emit
        # them anyway since the LVS reference convention here matches
        # what Magic exposes after ext2spice.
        f.write(f".subckt {top_name}")
        for tok in ports:
            f.write(f" {tok}")
        f.write("\n")

        # ---- Bitcell array instances (one Xbc per [row][col]) ----
        # Each bitcell connects:
        #   BL[c]  — column bit line   (analog read port)
        #   BLB[c] — column bit line bar
        #   WL[r]  — standard word line (write path)
        #   MWL[r] — multiply word line (CIM read path)
        #   MBL[c] — multiply bit line (analog accumulation)
        #   VPWR / VGND
        f.write(f"* {p.rows} x {p.cols} CIM bitcell array\n")
        for r in range(p.rows):
            for c in range(p.cols):
                f.write(
                    f"Xbc_{r}_{c} "
                    f"BL_{c} BLB_{c} WL_{r} MWL_{r} MBL_{c} "
                    f"VPWR VGND "
                    f"{bitcell_subckt}\n"
                )
        f.write("\n")

        # ---- MWL drivers (one per row) ----
        # Drives MWL[r] from MWL_EN[r] input.  Foundry buf_2 ports:
        # A (input), VGND, VNB (p-substrate body bias = VGND), VPB
        # (n-well body bias = VPWR), VPWR, X (output).
        f.write(f"* {p.rows} MWL drivers (foundry buf_2)\n")
        for r in range(p.rows):
            f.write(
                f"Xmwl_{r} MWL_EN[{r}] VGND VGND VPWR VPWR MWL_{r} "
                f"{mwl_driver_subckt}\n"
            )
        f.write("\n")

        # ---- MBL precharges (one per column) ----
        f.write(f"* {p.cols} MBL precharges\n")
        for c in range(p.cols):
            # cim_mbl_precharge port order: MBL_PRE VREF MBL VPWR
            # (VPWR ties the n-well via the cell's internal N-tap)
            f.write(
                f"Xpre_{c} MBL_PRE VREF MBL_{c} VPWR cim_mbl_precharge\n"
            )
        f.write("\n")

        # ---- MBL sense buffers (one per column) ----
        f.write(f"* {p.cols} MBL sense buffers\n")
        for c in range(p.cols):
            # cim_mbl_sense port order: VBIAS MBL VSS MBL_OUT VDD
            f.write(
                f"Xsense_{c} VBIAS MBL_{c} VGND MBL_OUT[{c}] VPWR "
                f"cim_mbl_sense\n"
            )
        f.write("\n")

        f.write(f".ends {top_name}\n")
    return out
