"""MBL sense buffer row for CIM macros.

Tiles `cols` MBL sense cells horizontally at the BOTTOM edge of the
array (one per column).  Each cell exposes a per-column MBL_OUT[col]
output plus shared VBIAS (analog bias) and supplies.

The MBL sense cell is generated by
`rekolektion.peripherals.cim_mbl_sense.generate_mbl_sense()` —
1.895 × 1.73 µm with internal labels `VBIAS`, `MBL`, `VSS`,
`MBL_OUT`, `VDD`.
"""
from __future__ import annotations

from typing import Optional

import gdstk

from rekolektion.peripherals.cim_mbl_sense import generate_mbl_sense
from rekolektion.macro.routing import draw_pin_with_label
from rekolektion.macro.sky130_drc import GDS_LAYER


_SENSE_CELL_NAME: str = "cim_mbl_sense"

# Internal label positions on the cim_mbl_sense cell (verified):
#   VBIAS   @ (0.170, 0.405) on poly  — bias gate
#   MBL     @ (0.170, 1.075) on poly  — driver gate (input from MBL[c])
#   VSS     @ (0.800, 0.155) on li1   — bottom S/D + body tap
#   MBL_OUT @ (0.800, 0.740) on li1   — middle S/D (source-follower out)
#   VDD     @ (0.800, 1.325) on li1   — top S/D
#   VSS     @ (1.720, 0.155) on met1  — P-tap met1 pad
_VBIAS_LX:   float = 0.170
_VBIAS_LY:   float = 0.405
_MBL_LX:     float = 0.170
_MBL_LY:     float = 1.075
_VSS_LX:     float = 0.800
_VSS_LY:     float = 0.155
_MBL_OUT_LX: float = 0.800
_MBL_OUT_LY: float = 0.740
_VDD_LX:     float = 0.800
_VDD_LY:     float = 1.325
_VSS_TAP_LX: float = 1.720
_VSS_TAP_LY: float = 0.155
_SENSE_CELL_W: float = 1.895
_SENSE_CELL_H: float = 1.730


class MBLSenseRow:
    """Row of `cols` MBL sense buffers at the bottom edge of the array."""

    def __init__(
        self,
        cols: int,
        col_pitch: float,
        name: Optional[str] = None,
    ):
        if cols < 1:
            raise ValueError(f"cols must be >= 1; got {cols}")
        if col_pitch <= 0:
            raise ValueError(f"col_pitch must be positive; got {col_pitch}")
        self.cols = cols
        self.col_pitch = col_pitch
        self.top_cell_name = name or f"cim_mbl_sense_row_{cols}"

    @property
    def cell_w(self) -> float:
        return _SENSE_CELL_W

    @property
    def cell_h(self) -> float:
        return _SENSE_CELL_H

    @property
    def width(self) -> float:
        return self.cols * self.col_pitch

    @property
    def height(self) -> float:
        return self.cell_h

    def build(self) -> gdstk.Library:
        lib = gdstk.Library(name=f"{self.top_cell_name}_lib")
        top = gdstk.Cell(self.top_cell_name)

        sense_cell, sense_lib = generate_mbl_sense()
        seen: set[str] = set()
        for c in sense_lib.cells:
            if c.name not in seen:
                lib.add(c.copy(c.name))
                seen.add(c.name)
        local_sense = next(c for c in lib.cells if c.name == _SENSE_CELL_NAME)

        # Cells may exceed col_pitch slightly — if so, place adjacent
        # cells with a column-skipping pitch (override col_pitch).
        # For SRAM-D col_pitch=1.925, cell_w=1.895 → fits with 0.030 µm
        # margin between cells.  For tighter pitches, the row builder
        # should warn rather than overlap.
        if self.cell_w > self.col_pitch:
            raise ValueError(
                f"cim_mbl_sense cell width {self.cell_w:.3f} exceeds "
                f"col_pitch {self.col_pitch:.3f}; cells would overlap"
            )

        x_offset = (self.col_pitch - self.cell_w) / 2.0
        for col in range(self.cols):
            origin = (col * self.col_pitch + x_offset, 0.0)
            top.add(gdstk.Reference(local_sense, origin=origin))

        # Horizontal shared-bus stripes spanning the full row width.
        # MBL is per-column so it does NOT get a horizontal stripe;
        # everything else (VBIAS, VSS, VDD, VSS-tap) is shared.
        row_w = self.cols * self.col_pitch
        poly_id, poly_dt = GDS_LAYER["poly"]
        li1_id, li1_dt = GDS_LAYER["li1"]
        m1_id, m1_dt = GDS_LAYER["met1"]
        _BUS_HALF = 0.075

        # VBIAS bus on poly at Y=_VBIAS_LY (0.405)
        top.add(gdstk.rectangle(
            (0.0, _VBIAS_LY - _BUS_HALF),
            (row_w, _VBIAS_LY + _BUS_HALF),
            layer=poly_id, datatype=poly_dt,
        ))
        # VSS bus on li1 at Y=_VSS_LY (0.155)
        top.add(gdstk.rectangle(
            (0.0, _VSS_LY - _BUS_HALF),
            (row_w, _VSS_LY + _BUS_HALF),
            layer=li1_id, datatype=li1_dt,
        ))
        # VDD bus on li1 at Y=_VDD_LY (1.325)
        top.add(gdstk.rectangle(
            (0.0, _VDD_LY - _BUS_HALF),
            (row_w, _VDD_LY + _BUS_HALF),
            layer=li1_id, datatype=li1_dt,
        ))
        # VSS-tap bus on met1 at Y=_VSS_TAP_LY (0.155) — same Y as the
        # VSS li1 bus, providing met1 backbone for vertical PDN reach.
        top.add(gdstk.rectangle(
            (0.0, _VSS_TAP_LY - _BUS_HALF),
            (row_w, _VSS_TAP_LY + _BUS_HALF),
            layer=m1_id, datatype=m1_dt,
        ))

        # Pin shapes at the cell's actual pin coordinates and layers.
        # Pin layers per the cell:
        #   VBIAS, MBL : poly
        #   VSS, MBL_OUT, VDD : li1
        #   VSS (tap) : met1
        _PIN_HALF = 0.07
        for col in range(self.cols):
            x_origin = col * self.col_pitch + x_offset

            # VBIAS — shared bias bus across all sense cells (poly gate)
            cx = x_origin + _VBIAS_LX
            cy = _VBIAS_LY
            draw_pin_with_label(
                top, text="VBIAS", layer="poly",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # MBL[col] — per-column input gate
            cx = x_origin + _MBL_LX
            cy = _MBL_LY
            draw_pin_with_label(
                top, text=f"MBL[{col}]", layer="poly",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # VSS — body + bias source, on li1
            cx = x_origin + _VSS_LX
            cy = _VSS_LY
            draw_pin_with_label(
                top, text="VSS", layer="li1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # MBL_OUT[col] — per-column output, on li1
            cx = x_origin + _MBL_OUT_LX
            cy = _MBL_OUT_LY
            draw_pin_with_label(
                top, text=f"MBL_OUT[{col}]", layer="li1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # VDD — driver drain (PMOS-side), on li1
            cx = x_origin + _VDD_LX
            cy = _VDD_LY
            draw_pin_with_label(
                top, text="VDD", layer="li1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

            # VSS at the P-tap, on met1
            cx = x_origin + _VSS_TAP_LX
            cy = _VSS_TAP_LY
            draw_pin_with_label(
                top, text="VSS", layer="met1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

        lib.add(top)
        return lib
