"""MWL driver column for CIM macros.

Stacks `rows` MWL driver cells vertically (one per bitcell row), with
each driver pitched to the CIM bitcell's row pitch.  Exposes one
`MWL_EN[row]` port per row plus per-cell VPWR/VGND .pin shapes (for
LVS port matching, mirroring v2 SRAM's wl_driver_row pattern).

The MWL driver cell is generated by
`rekolektion.peripherals.cim_mwl_driver.generate_mwl_driver()` —
2.09 × 2.04 µm, with internal labels `MWL_EN`, `MWL`, `VSS`, `VDD`.
"""
from __future__ import annotations

from typing import Optional

import gdstk

from rekolektion.peripherals.cim_mwl_driver import generate_mwl_driver
from rekolektion.macro.routing import draw_pin_with_label


_MWL_CELL_NAME: str = "cim_mwl_driver"
# Internal label positions on the foundry-style MWL driver cell.
# These were inspected via `cell.labels` after generate_mwl_driver():
#   MWL_EN — gate input, used as the per-row port hook
#   MWL    — output that drives the bitcell row
#   VDD/VSS — supply rails
# We rely on the cell's existing labels for the bus connection (MWL out
# abuts the bitcell row's MWL pin via cell-to-cell adjacency); the row
# builder only needs to wrap them with .pin shapes for Magic port
# promotion at the parent extraction.


class MWLDriverRow:
    """Stack of MWL drivers (one per row) on the LEFT side of the array."""

    def __init__(
        self,
        rows: int,
        row_pitch: float,
        name: Optional[str] = None,
    ):
        if rows < 1:
            raise ValueError(f"rows must be >= 1; got {rows}")
        if row_pitch <= 0:
            raise ValueError(f"row_pitch must be positive; got {row_pitch}")
        self.rows = rows
        self.row_pitch = row_pitch
        self.top_cell_name = name or f"cim_mwl_driver_col_{rows}"

    @property
    def driver_w(self) -> float:
        return 2.09  # cim_mwl_driver cell width (verified)

    @property
    def driver_h(self) -> float:
        return 2.04  # cim_mwl_driver cell height (verified)

    @property
    def width(self) -> float:
        return self.driver_w

    @property
    def height(self) -> float:
        # Each driver placed on its own row at row_pitch.  We center the
        # driver in the row's vertical span; total height covers all rows.
        return self.rows * self.row_pitch

    def build(self) -> gdstk.Library:
        lib = gdstk.Library(name=f"{self.top_cell_name}_lib")
        top = gdstk.Cell(self.top_cell_name)

        drv_cell, drv_lib = generate_mwl_driver()
        # Import the driver cell + its dependencies into our library.
        seen: set[str] = set()
        for c in drv_lib.cells:
            if c.name not in seen:
                lib.add(c.copy(c.name))
                seen.add(c.name)
        local_drv = next(c for c in lib.cells if c.name == _MWL_CELL_NAME)

        # Place one driver per bitcell row, vertically centred on the
        # row's pitch span.  Y origin = row_index * row_pitch.
        # The driver cell's MWL output abuts the bitcell row at its
        # right edge by cell-to-cell adjacency.
        for row in range(self.rows):
            origin = (0.0, row * self.row_pitch)
            top.add(gdstk.Reference(local_drv, origin=origin))

        # Per-row MWL_EN .pin shape on met2 so the row_decoder/parent
        # macro can wire to each driver individually.  The driver cell
        # already labels its internal MWL_EN node; here we add a
        # parent-visible .pin pad over that label so Magic exposes
        # MWL_EN[row] as a row-decoder-callable port.
        # Pin position: cell-local LEFT edge (x=0) at the gate input y.
        # For the MWL_EN gate the input y is at the cell's vertical
        # midpoint (driver_h/2) — same y at the parent level after
        # row_index translation.
        from rekolektion.macro.routing import draw_pin
        _PIN_HALF = 0.07
        for row in range(self.rows):
            cy = row * self.row_pitch + self.driver_h / 2.0
            # Place the .pin slightly inside the WEST edge of the driver
            # (x=0.10) so the rect lies on the MWL_EN gate's li1 pad.
            cx = 0.10
            draw_pin_with_label(
                top, text=f"MWL_EN[{row}]", layer="met1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

        # VPWR / VGND .pin shapes per driver (pattern matching v2
        # wl_driver_row / row_decoder).  Each driver's VDD/VSS labels
        # are at known cell-local positions; .pin pads ensure Magic
        # promotes the row-cell's supply nets as ports.
        # NOTE: exact VDD/VSS label coordinates are read from the
        # generated mwl_driver cell — see comment in cim_mwl_driver.py.
        # We place the pin pads slightly inside the cell at the supply
        # row y values.
        _SUPPLY_HALF = 0.06
        for row in range(self.rows):
            row_y = row * self.row_pitch
            # VDD typically at cell-local (driver_w/2, driver_h - 0.1)
            vdd_cx, vdd_cy = self.driver_w / 2.0, row_y + self.driver_h - 0.10
            vss_cx, vss_cy = self.driver_w / 2.0, row_y + 0.10
            draw_pin_with_label(
                top, text="VPWR", layer="met1",
                rect=(vdd_cx - _SUPPLY_HALF, vdd_cy - _SUPPLY_HALF,
                      vdd_cx + _SUPPLY_HALF, vdd_cy + _SUPPLY_HALF),
            )
            draw_pin_with_label(
                top, text="VGND", layer="met1",
                rect=(vss_cx - _SUPPLY_HALF, vss_cy - _SUPPLY_HALF,
                      vss_cx + _SUPPLY_HALF, vss_cy + _SUPPLY_HALF),
            )

        lib.add(top)
        return lib
