"""MBL precharge row for CIM macros.

Tiles `cols` MBL precharge cells horizontally (one per bitcell column),
sitting at the TOP edge of the array.  Mirrors v2 SRAM's
PrechargeRow pattern — a single common control signal (`MBL_PRE`)
plus per-column MBL connections (auto-abutted to the array's MBL
columns) and a global VREF.

The MBL precharge cell is generated by
`rekolektion.peripherals.cim_mbl_precharge.generate_mbl_precharge()` —
1.20 × 1.17 µm with internal labels `MBL_PRE`, `VREF`, `MBL`.
"""
from __future__ import annotations

from typing import Optional

import gdstk

from rekolektion.peripherals.cim_mbl_precharge import generate_mbl_precharge
from rekolektion.macro.routing import draw_pin_with_label


_PRE_CELL_NAME: str = "cim_mbl_precharge"


class MBLPrechargeRow:
    """Row of `cols` MBL precharge cells across the top of the array."""

    def __init__(
        self,
        cols: int,
        col_pitch: float,
        name: Optional[str] = None,
    ):
        if cols < 1:
            raise ValueError(f"cols must be >= 1; got {cols}")
        if col_pitch <= 0:
            raise ValueError(f"col_pitch must be positive; got {col_pitch}")
        self.cols = cols
        self.col_pitch = col_pitch
        self.top_cell_name = name or f"cim_mbl_precharge_row_{cols}"

    @property
    def cell_w(self) -> float:
        return 1.20

    @property
    def cell_h(self) -> float:
        return 1.17

    @property
    def width(self) -> float:
        return self.cols * self.col_pitch

    @property
    def height(self) -> float:
        return self.cell_h

    def build(self) -> gdstk.Library:
        lib = gdstk.Library(name=f"{self.top_cell_name}_lib")
        top = gdstk.Cell(self.top_cell_name)

        pre_cell, pre_lib = generate_mbl_precharge()
        seen: set[str] = set()
        for c in pre_lib.cells:
            if c.name not in seen:
                lib.add(c.copy(c.name))
                seen.add(c.name)
        local_pre = next(c for c in lib.cells if c.name == _PRE_CELL_NAME)

        # Place one precharge per column at col_pitch.  Centre each cell
        # in the column's pitch (so the cell's MBL output sits roughly
        # at the column's bitcell MBL x position).
        x_offset = (self.col_pitch - self.cell_w) / 2.0
        for col in range(self.cols):
            origin = (col * self.col_pitch + x_offset, 0.0)
            top.add(gdstk.Reference(local_pre, origin=origin))

        # MBL_PRE bus: shared control signal across all precharges.
        # The cell's internal MBL_PRE label is at a known position —
        # we wrap it with a per-column .pin so Magic exposes a
        # row-wide MBL_PRE port (single net spanning all cells).
        # MBL_PRE is on poly (gate input).  We place a .pin pad in
        # the centre of each cell at MBL_PRE's y.
        _PIN_HALF = 0.07
        for col in range(self.cols):
            cx = col * self.col_pitch + x_offset + self.cell_w / 2.0
            cy = self.cell_h / 2.0   # MBL_PRE label is roughly mid-height
            draw_pin_with_label(
                top, text="MBL_PRE", layer="met1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

        # VREF rail .pin per cell — VREF is shared across all
        # precharges (the precharge target voltage).  Same pattern.
        for col in range(self.cols):
            cx = col * self.col_pitch + x_offset + self.cell_w / 2.0
            cy = self.cell_h - 0.10  # VREF rail at the cell top
            draw_pin_with_label(
                top, text="VREF", layer="met1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

        # Per-column MBL[i] .pin shape — each precharge cell's MBL
        # output anchors to a specific bitcell column.  Naming with
        # bus index lets the parent macro and the reference SPICE
        # match positionally.
        for col in range(self.cols):
            cx = col * self.col_pitch + x_offset + self.cell_w / 2.0
            cy = 0.10  # MBL output at the cell bottom (toward the array)
            draw_pin_with_label(
                top, text=f"MBL[{col}]", layer="met1",
                rect=(cx - _PIN_HALF, cy - _PIN_HALF,
                      cx + _PIN_HALF, cy + _PIN_HALF),
            )

        lib.add(top)
        return lib
