/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSEDSIGNAL */
/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module sky130_ef_sc_hd__decap_12();
endmodule

module sky130_ef_sc_hd__fakediode_2(DIODE);
  input DIODE;
  wire DIODE;
endmodule

module sky130_ef_sc_hd__fill_12();
endmodule

module sky130_ef_sc_hd__fill_8();
endmodule

/* verilator lint_on UNUSEDSIGNAL */
/* verilator lint_on UNDRIVEN */

