#!/usr/bin/env python3
"""End-to-end demo of the .rkt-native primitive + block workflow.

Walks through the full hand-off described in docs/io/rkt.md:

  1. Mint two PDK primitives (an HV nfet and an HV pfet) via the
     Python generators that shell out to Magic. Both cells land in
     `<out>/primitives/*.rkt` with `(meta ...)` provenance.

  2. Compose a tiny parent block (`demo_2fet`) that imports those
     primitives and SRefs them with simple translations + a single
     parent-paint met1 strap to show how block-level geometry mixes
     with imported cells. Lands in `<out>/demo_2fet.rkt`.

  3. Print the path. Opening it in the viz tool — `dotnet run --project
     tools/viz/src/Rekolektion.Viz.Cli -- app <path>` — resolves the
     imports and renders the composed silicon-truth view.

Run:
    .venv/bin/python scripts/demo_primitive_workflow.py [out_dir]

The default `out_dir` is `./demo_output/`. The script is idempotent —
re-running uses the cache (no Magic spawn unless params change).
"""

from __future__ import annotations

import sys
from pathlib import Path

from rekolektion.io import rkt
from rekolektion.primitives.sky130 import gen_nfet_hv, gen_pfet_hv


def build_demo_block(out_dir: Path) -> Path:
    """Mint primitives, write the parent block .rkt, return its path."""

    primitives_dir = out_dir / "primitives"

    # Step 1: mint primitives. These calls are cache-aware — same params
    # in a later run skip Magic entirely.
    nfet_name = gen_nfet_hv(
        w_um=1.2, l_um=1.0, guard=False, primitives_dir=primitives_dir
    )
    pfet_name = gen_pfet_hv(
        w_um=1.2, l_um=1.0, guard=False, primitives_dir=primitives_dir
    )

    # Step 2: compose the parent block. Imports are relative to the
    # block .rkt's own location — the viz tool resolves them when
    # loading. SRef origins are in DBU (nm here); the demo offsets the
    # pfet to sit 4 µm to the right of the nfet so they don't overlap.
    nfet_offset_dbu = 0
    pfet_offset_dbu = 4_000  # 4 µm

    # The met1 strap bridges the gap between the two FETs at y≈0.
    # Coordinates are deliberately conservative — this is a layout
    # toy, not a manufacturable cell. Real cells use the design-rule
    # tables in src/rekolektion/tech/sky130.py.
    strap_x1 = nfet_offset_dbu + 1_055  # nfet's right edge
    strap_x2 = pfet_offset_dbu - 1_055  # pfet's left edge
    strap_y1 = -150
    strap_y2 = 150

    block = rkt.Document(
        imports=[
            rkt.Import(path=f"primitives/{nfet_name}.rkt"),
            rkt.Import(path=f"primitives/{pfet_name}.rkt"),
        ],
        cells=[
            rkt.Cell(
                name="demo_2fet",
                comments=[
                    "Demo: two HV FETs placed side by side with a met1",
                    "strap bridging the gap. Not a real circuit — meant to",
                    "exercise primitive-import + parent-paint composition.",
                ],
                elements=[
                    rkt.SRef(
                        cell=nfet_name,
                        origin=(nfet_offset_dbu, 0),
                    ),
                    rkt.SRef(
                        cell=pfet_name,
                        origin=(pfet_offset_dbu, 0),
                    ),
                    rkt.Rect(
                        layer=rkt.named("sky130", "met1"),
                        x1=strap_x1,
                        y1=strap_y1,
                        x2=strap_x2,
                        y2=strap_y2,
                    ),
                ],
            ),
        ],
        top_cell="demo_2fet",
        header_comments=[
            "Generated by scripts/demo_primitive_workflow.py.",
            "Two PDK-minted primitives + one parent-paint met1 strap.",
        ],
    )

    block_path = out_dir / "demo_2fet.rkt"
    out_dir.mkdir(parents=True, exist_ok=True)
    block_path.write_text(rkt.write(block), encoding="utf-8")
    return block_path


def main(argv: list[str]) -> int:
    out_dir = Path(argv[1]) if len(argv) > 1 else Path.cwd() / "demo_output"
    out_dir = out_dir.resolve()

    print(f"Generating demo workflow at {out_dir}")
    block_path = build_demo_block(out_dir)
    primitive_files = sorted((out_dir / "primitives").glob("*.rkt"))

    print()
    print("Primitives:")
    for p in primitive_files:
        size = p.stat().st_size
        print(f"  {p.relative_to(out_dir)}  ({size} bytes)")
    print()
    print(f"Block: {block_path.relative_to(out_dir)}")
    print()
    print("Open in the viz tool:")
    print(f"  dotnet run --project tools/viz/src/Rekolektion.Viz.Cli "
          f"-- app {block_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
